#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -x "$basedir/node" ]; then
  exec "$basedir/node"  "$basedir/../../../../../bunyan@1.8.15/node_modules/bunyan/bin/bunyan" "$@"
else
  exec node  "$basedir/../../../../../bunyan@1.8.15/node_modules/bunyan/bin/bunyan" "$@"
fi
