/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/map`; params?: Router.UnknownInputParams; } | { pathname: `/sign-in`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/map` | `/map`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/challenge/new` | `/challenge/new`; params?: Router.UnknownInputParams; } | { pathname: `/challenge/new`; params?: Router.UnknownInputParams; } | { pathname: `/closet`; params?: Router.UnknownInputParams; } | { pathname: `/skate/leaderboard`; params?: Router.UnknownInputParams; } | { pathname: `/skate/new`; params?: Router.UnknownInputParams; } | { pathname: `/skate/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/map`; params?: Router.UnknownOutputParams; } | { pathname: `/sign-in`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/map` | `/map`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/challenge/new` | `/challenge/new`; params?: Router.UnknownOutputParams; } | { pathname: `/challenge/new`; params?: Router.UnknownOutputParams; } | { pathname: `/closet`; params?: Router.UnknownOutputParams; } | { pathname: `/skate/leaderboard`; params?: Router.UnknownOutputParams; } | { pathname: `/skate/new`; params?: Router.UnknownOutputParams; } | { pathname: `/skate/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/map${`?${string}` | `#${string}` | ''}` | `/sign-in${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/map${`?${string}` | `#${string}` | ''}` | `/map${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/challenge/new${`?${string}` | `#${string}` | ''}` | `/challenge/new${`?${string}` | `#${string}` | ''}` | `/challenge/new${`?${string}` | `#${string}` | ''}` | `/closet${`?${string}` | `#${string}` | ''}` | `/skate/leaderboard${`?${string}` | `#${string}` | ''}` | `/skate/new${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/map`; params?: Router.UnknownInputParams; } | { pathname: `/sign-in`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/map` | `/map`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/challenge/new` | `/challenge/new`; params?: Router.UnknownInputParams; } | { pathname: `/challenge/new`; params?: Router.UnknownInputParams; } | { pathname: `/closet`; params?: Router.UnknownInputParams; } | { pathname: `/skate/leaderboard`; params?: Router.UnknownInputParams; } | { pathname: `/skate/new`; params?: Router.UnknownInputParams; } | `/skate/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/skate/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
